# Generated by Django 2.2 on 2019-12-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_rate_source_abbr_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ratelog',
            constraint=models.UniqueConstraint(fields=('source', 'ts', 'base', 'code'), name='rate_log_unique_cst'),
        ),
        migrations.AddConstraint(
            model_name='ratelog',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, rate__lte=0), name='rate_log_negative_or_zero_rate_cst'),
        ),
    ]
