# Generated by Django 2.2 on 2019-12-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_rate_log_contraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratelog',
            name='rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
